namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_CHAIN_ID?: "mainnet";

    NEXT_PUBLIC_ALCHEMY_API_KEY: string;
    NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: string;

    NEXT_PUBLIC_UPDWN_CONTRACT_ADDRESS: string;
    NEXT_PUBLIC_TOKEN_MINTER_CONTRACT_ADDRESS: string;
    NEXT_PUBLIC_GAME_ENGINE_CONTRACT_ADDRESS: string;
    NEXT_PUBLIC_PRICE_FEED_CONTRACT_ADDRESS: string;
    NEXT_PUBLIC_TREASURY_CONTRACT_ADDRESS: string;
  }
}
